import frappe

def get_context(context):
	context.schedules = [
		[
			["October 17, 2019", "Enterprise + Open Source"],
			["08:00 - 09:30", "Registrations & Breakfast"],
			["09:45 - 10:00", "Opening Ceremony, Welcome"],
			["10:00 - 10:30", "Dr. Kailash Nadh (CTO, Zerodha)"],
			["", "<span class='text-muted'>Thoughts on FOSS and \"enterprise\"</span>"],
			["10:40 - 11:10", "Prof. Satish Annegiri (Registrar, VTU)"],
			["", "<span class='text-muted'>Role of FOSS in Higher Education</span>"],
			["11:10 - 11:40", "Nikhil Sharma (VP,  Elastic Run)"],
			["", "<span class='text-muted'>Open Enterprises</span>"],
			["11:40 - 12:00", "Prashant Soni (IT Head, AWGP)"],
			["", "<span class='text-muted'>Deploying ERPNext at AWGP</span>"],
			["12:00 - 12:30", "Rushabh Mehta (Founder & CEO, Frappe)"],
			["", "<span class='text-muted'>A Company Without Managers</span>"],
			["12:30 - 13:40", "Lunch Break"],
			["13:40 - 14:10", "Umair Sayed & Nabin Hait"],
			["", "<span class='text-muted'>ERPNext v12 and Release Process</span>"],
			["14:10 - 14:40", "Basawaraj & Jai Chavan "],
			["", "<span class='text-muted'>Enterprise Deployments by Frappe</span>"],
			["14:40 - 15:10", "Kai Rödiger, Jonas Depoix & Mario Truss (Tech team, //Seibert /Media)"],
			["", "<span class='text-muted'>A small glimpse into our ERPNext Journey</span>"],
			["15:10 - 15:30", "Richa Verma (Independent Data Consultant)"],
			["", "<span class='text-muted'>Choosing ERPNext over no/low code ERP systems</span>"],
			["15:30 - 15:50", "Snacks Break"],
			["15:50 - 16:10", "Aditya Hase (Engineer, Frappe)"],
			["", "<span class='text-muted'>Dynamic Scaling with ERPNext</span>"],
			["16:10 - 16:30", "Himanshu Mishra & Ajit Pendse (Tech team, ElasticRun)"],
			["", "<span class='text-muted'>Scaled in 60 seconds</span>"],
			["16:30 - 17:00", "Enterprise Panel"],
			["", "<span class='text-muted'>Way forward for ERPNext (Kailash, Nikhil, Prashant, Rushabh)</span>"],
			["17:00 - 17:30", "Proceed towards dinner venue"],
			["18:30 - 20:30", "Dinner and Discussions/Karaoke"],
		],
		[
			["October 18th, 2019" ,"User Stories, Partners, and Foundation"],
			["08:00 - 09:30" ,"Breakfast"],
			["10:00 - 10:30" ,"Keynote by Rushabh Mehta (Founder & CEO, Frappe)"],
			["", "<span class='text-muted'>What's next for Frappe?</span>"],
			["10:30 - 11:00" ,"Keynote by Ketan & Smital (VP for Partner & Alliances, Frappe)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:00 - 11:30" ,"Keynote by Anton (CEO, PT Nusantara)"],
			["", "<span class='text-muted'>My ERPNext Mission</span>"],
			["11:30 - 11:50" ,"Kanhaiya Kale (Director, Indictrans)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:50 - 12:10" ,"Sharmaake (CEO, iKit Solutions)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["12:10 - 12:30" ,"SMB Solutions (Partner Talk)"],
			["", "<span class='text-muted'>Seven Wonders of ERPNext Implementation Challenges</span>"],
			["12:30 - 13:45" ,"Lunch Break"],
			["13:45 - 14:15", "Community Awards"],
			["", "<span class='text-muted'>Awards to top contributors</span>"],
			["14:15 - 15:15" ,"Unconference"],
			["", "<span class='text-muted'>Open Mic</span>"],
			["15:15 - 15:40" ,"Snacks Break"],
			["15:40 - 16:00" ,"Unconference"],
			["", "<span class='text-muted'>Open Mic</span>"],
			["16:00 - 16:50" ,"Community Panel & Open Discussions"],
			["", "<span class='text-muted'>Way forward for ERPNext</span>"],
			["16:50 - 17:00" ,"Closing Notes"],
			["17:00 - 17:30" ,"Proceed towards dinner venue"],
			["18:30 - 20:30" ,"Dinner and Discussions"],
		]
	]

	context.schedule_row_styles = {
		"15:30 - 15:50": "style='background-color: #EDF2F7'",
		"12:30 - 13:40": "style='background-color: #EDF2F7'",
		"12:30 - 13:45": "style='background-color: #EDF2F7'",
		"15:15 - 15:40": "style='background-color: #EDF2F7'",
	}
