import frappe

def get_context(context):
	context.schedules = [
		[
			["October 17, 2019", "Enterprise + Open Source"],
			["08:00 - 09:30", "Registrations & Breakfast"],
			["09:45 - 10:00", "Opening Ceremony, Welcome"],
			["10:00 - 10:30", "Dr. Kailash Nadh (CTO, Zerodha)"],
			["", "<span class='text-muted'>Thoughts on FOSS and \"enterprise\"</span>"],
			["10:40 - 11:10", "Prof. Satish Annegiri (Registrar, VTU)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:15 - 11:45", "Nikhil Sharma (VP,  Elastic Run)"],
			["", "<span class='text-muted'>Open Enterprises</span>"],
			["12:00 - 12:30", "Prashant Soni (IT Head, AWGP)"],
			["", "<span class='text-muted'>Deploying ERPNext at AWGP</span>"],
			["12:45 - 13:45", "Lunch Break"],
			["14:00 - 14:20", "Umair Sayed & Nabin Hait"],
			["", "<span class='text-muted'>ERPNext v12 and Release Process</span>"],
			["14:25 - 14:40", "Basawaraj & Jai Chavan "],
			["", "<span class='text-muted'>Enterprise Deployments by Frappe</span>"],
			["14:45 - 15:15", "Kai Rödiger, Jonas Depoix & Mario Trvss (Tech team, //Seibert /Media)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["15:20 - 15:35", "Richa Verma (Independent Data Consultant)"],
			["", "<span class='text-muted'>Choosing ERPNext over no/low code ERP systems</span>"],
			["15:40 - 15:55", "Rushabh Mehta (Founder & CEO, Frappe)"],
			["", "<span class='text-muted'>Energy Points System</span>"],
			["15:55 - 16:10", "Snacks Break"],
			["16:15- 16:25", "Aditya Hase (Engineer, Frappe)"],
			["", "<span class='text-muted'>Dynamic Scaling with ERPNext</span>"],
			["16:25- 16:40", "Himanshu Mishra & Ajit Pendse (Tech team, ElasticRun)"],
			["", "<span class='text-muted'>Scaled in 60 seconds</span>"],
			["16:40 - 17:00", "Enterprise Panel"],
			["", "<span class='text-muted'>Way forward for ERPNext (Kailash, Nikhil, Prashant, Rushabh)</span>"],
			["17:00 - 17:30", "Proceed towards dinner venue"],
			["18:30 - 20:30", "Dinner and Discussions/Karaoke"],
		],
		[
			["October 18th, 2019" ,"User Stories, Partners, and Foundation"],
			["08:00 - 09:30" ,"Breakfast"],
			["10:00 - 10:30" ,"Keynote by Rushabh Mehta (Founder & CEO, Frappe)"],
			["", "<span class='text-muted'>What's next for Frappe?</span>"],
			["10:40 - 11:00" ,"Keynote by Ketan & Smital (VP for Partner & Alliances, Frappe)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:05 - 11:35" ,"Keynote by Anton (CEO, PT Nusantara)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:40 - 12:00" ,"Kanhaiya Kale (Director, Indictrans)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["11:40 - 12:00" ,"Sharmaake (Partner, iKit Solutions)"],
			["", "<span class='text-muted'><i>To Be Announced</i></span>"],
			["12:45 - 13:45" ,"Lunch Break"],
			["14:00 - 14:30", "Rushabh Mehta"],
			["", "<span class='text-muted'>Free Software vs Open Source Software</span>"],
			["14:35 - 14:50" ,"Community Panel"],
			["", "<span class='text-muted'>Way forward for ERPNext</span>"],
			["14:55 - 15:15" ,"Unconference"],
			["", "<span class='text-muted'>Open Mic</span>"],
			["15:20 - 15:50" ,"Unconference"],
			["", "<span class='text-muted'>Open Mic</span>"],
			["15:55 - 16:15" ,"Snacks Break"],
			["16:20- 16:50" ,"Unconference"],
			["", "<span class='text-muted'>Open Mic</span>"],
			["16:50 - 17:00" ,"Closing Notes"],
			["17:00 - 17:30" ,"Proceed towards dinner venue"],
			["18:30 - 20:30" ,"Dinner and Discussions"],
		]
	]

	context.schedule_row_styles = {
		"15:55 - 16:15": "style='background-color: #EDF2F7'",
		"12:45 - 13:45": "style='background-color: #EDF2F7'"
	}
